### ISSUE TITLE
QOL Change - Readability 

### ISSUE THREAD

**Issue by kdk1116** [nemanjarogic/DesignPatternsLibrary#5]
Hello,

I found a little bit of a nuisance in that if you want to check the output of whichever design pattern it would pass the ouput for the default console because there are too many patterns. 

![image](https://user-images.githubusercontent.com/59551056/208329408-323689e8-de28-4b34-83cc-55f3f652e84f.png)

This can be easily fixed by adding a `Console.ReadLine()` after the execution has completed (see [PR](https://github.com/nemanjarogic/DesignPatternsLibrary/pull/4))

Its a small fix but might help others to avoid debugging. I originally thought there was a bug since I couldn't see why the app re-entered the loop.

**Comment by nemanjarogic** [comment]
Thanks for reporting the issue. I haven't seen that the behavior won't be obvious for some people, but I totally agree with your comments.

**Comment by nemanjarogic** [comment]
I merged the PR. Thanks for reporting the issue and the contribution.

**Comment by kdk1116** [comment]
> I merged the PR. Thanks for reporting the issue and the contribution.

Thanks for making this awesome library!
